# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa2e54540eae292524487ec09c2c257e9a40b414b46af12d7b508b2b0a73e32b33afb736e3a7db81ca4dcb0bc037f3dcd482ad054cbb8e43324fd9d2be296f0

test:
  secret_key_base: 55350fe52fb8dfb2ce4c46738d0a92fee5e67953c15fd88b643a15ea1298a22a41386df92e3d0cdb8fb14224410aad3b9f83a618b10794f5519b074ba985e1c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
