# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe212386bec914517c63010a1606f2a128ce63f9c9a372bcaecaaa28aa9b7e20b5ba7fec6a3a4631521e9a08f842987a873d6e968296f1ff21a4ae775d9fbc6

test:
  secret_key_base: cb2681d346a67e2b4af08c1c32e33d9662304c578ddfd97b10df14e7ed5ad1f3f0cf9ba01ecd96d71fd4f266921ee17126b7d86ea8089aabf70fc72e09a934f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
